import os
import subprocess
import time

def process_images(images_dir, encrypt_script, decrypt_script, encryption_dir):
    total_encrypt_time = 0
    total_decrypt_time = 0
    image_count = 0

    for filename in os.listdir(images_dir):
        if filename.endswith((".png", ".jpg", ".jpeg")):  # Add other image formats if needed
            image_path = os.path.join(images_dir, filename)
            image_count += 1

            # Encrypt the image
            start_time = time.time()
            subprocess.run(['python3', encrypt_script, image_path])
            encrypt_time = time.time() - start_time
            total_encrypt_time += encrypt_time

            # Decrypt the image
            start_time = time.time()
            subprocess.run(['python3', decrypt_script])
            decrypt_time = time.time() - start_time
            total_decrypt_time += decrypt_time

            # Delete intermediate files generated by encrypt.py and decrypt.py
            for file in ['encrypted_data.bin', 'image_shape.txt', 'key.bin', 'iv.bin', 'decrypted_image.jpg']:
                file_path = os.path.join(encryption_dir, file)
                if os.path.exists(file_path):
                    os.remove(file_path)

            print(f"Processed {filename}. Encryption time: {encrypt_time:.2f}s, Decryption time: {decrypt_time:.2f}s")

    # Calculate and print average times
    if image_count > 0:
        avg_encrypt_time = total_encrypt_time / image_count
        avg_decrypt_time = total_decrypt_time / image_count
        print(f"Average Encryption Time: {avg_encrypt_time:.2f}s")
        print(f"Average Decryption Time: {avg_decrypt_time:.2f}s")
    else:
        print("No images were processed.")

# Paths
images_dir = '/home/jigyas/Github/Data-Privacy-and-Data-Security-Models/Image_Encryption/Testing/Testing_images'
encrypt_script = '/home/jigyas/Github/Data-Privacy-and-Data-Security-Models/Image_Encryption/Testing/encrypt.py'
decrypt_script = '/home/jigyas/Github/Data-Privacy-and-Data-Security-Models/Image_Encryption/Testing/decrypt.py'
encryption_dir = '/home/jigyas/Github/Data-Privacy-and-Data-Security-Models/Image_Encryption/Testing'

process_images(images_dir, encrypt_script, decrypt_script, encryption_dir)
